[package]
name = "avid-rustacean-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
avid-rustacean-model = { path = "../model", features = ["server"] }
axum = { version = "0.6", features = ["macros"] }
shuttle-runtime = { version = "0.35.1" }
shuttle-shared-db = { version = "0.35.1", features = ["mongodb"] }
shuttle-axum = { version = "0.35.1" }
tokio = { version = "1.28", features = ["sync"] }
serde = { version = "1.0", features = ["rc"] }
serde_json = { version = "1.0" }
mongodb = { version = "2.3", features = ["tokio-runtime"] }
futures = "0.3"
troupe = "0.1.0"
tower-http = { version = "0.4.4", features = ["cors"] }
http = { version = "1.0" }
tracing = "0.1.40"
shuttle-secrets = "0.35.1"
sha2 = "0.10.8"
hex-literal = "0.4.1"

[build-dependencies]
flate2 = "1.0"
