name: Avid Rustacean Deployment

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deployment:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
